### PR TITLE
Resident feature

### PR DESCRIPTION
**Pull request by LBHSPreston**
# What
- Added a new resident feature providing the standard REST operations:
- GET - residents (search residents)
- GET - residents/{id} (get a single resident by id)
- POST - residents (create a new resident)
- PATCH - residents/{id} (update the resident with the specified id)

# Why
- These endpoints are required to work with resident data via the API.  It is part of the new feature set that allow the saving of residents' information separate from the requests they make.

# Screenshots

# Link to ticket
https://trello.com/c/FoIGcpjg/246-api-resident-endpoints

# Notes

### CODE REVIEW

**Comment by kosiakkatrina** [comment]
I'm getting Id: 0 for all the residents I'm trying to get in `V4/residents/:id` path 🤔 
image

**Comment by LBHSPreston** [comment]
Ah I think I fixhed that in resident help requests branch.

**Comment by kosiakkatrina** [comment]
Also, I'm not sure how to query search endpoint (I also couldn't find it)
Doing it like so just gives me `method not allowed 405`:
GET /api/V4/residents?firstName=new

**Review by kosiakkatrina — APPROVED** [review]

**Comment by LBHSPreston** [comment]
also fixed in the help request branch.

**Pull request merged**
